import { Component } from "@angular/core"
import { ChatService } from "../../../services/chat.service"
import { Message } from "../../../models/message.model"
@Component({
	selector: "chat-add",
	standalone: false,
	templateUrl: "./chat-add.component.html",
	styleUrl: "./chat-add.component.scss",

})
export class ChatAddComponent {
	userInput: string = "" // Local state for the input

	constructor(private chatService: ChatService) {}

	sendMessageToServer(): void {
		const text = this.userInput.trim()
		if (!text) return

		const message: Message = {
			_id: "", // Will be generated by the service/backend
			sentAt: new Date(),
			from: "user",
			question: text,
		}

		this.chatService.save(message).subscribe({
			next: () => {
				this.userInput = "" // Clear input on successful send
			},
			error: (err) => console.error("Error sending message:", err),
		})
	}
}
